
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.WindowConstants;
// date packages import
import java.lang.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.*;

import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Diksha More
 */
public class Home extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs ;


    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        // database connection
         String url = "jdbc:mysql://localhost:3306/expensetracking"; // Database URL (use the database you created)
		        String username = "root"; // Default MySQL username
		        String password = ""; // Default MySQL password (empty by default on WAMP)

		        try {
		            // Step 1: Load the MySQL JDBC driver
		            Class.forName("com.mysql.cj.jdbc.Driver");

		            // Step 2: Establish the connection
		            Connection con = DriverManager.getConnection(url, username, password);
		            System.out.println("Connected to the database.");

		            
		            // Step 5: Close the connection
		            con.close();
		        } catch (Exception e) {
		        	e.printStackTrace();
		        }
        //close of database connection
        
        // display current date
       
         try
         {
                SimpleDateFormat d=new SimpleDateFormat("dd-MM-yyy");
                String cd=d.format(new Date());
                t3.setFont(new java.awt.Font("Tahoma", 0, 18));
                t3.setText(cd);
       
         }catch(Exception e)
        {
                System.out.println(e); 
        }
// close display current date

t2.addKeyListener(new java.awt.event.KeyAdapter() {
    public void keyReleased(java.awt.event.KeyEvent evt) {
        t2KeyReleased(evt);
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        l6 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        b2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 0, 255));
        l1.setText("ID");

        l2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 0, 255));
        l2.setText("Owner Name");

        l3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l3.setText("Date");

        l4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l4.setText("Description");

        l5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        l5.setText("Amt");

        b1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 255));
        b1.setText("Add");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        t3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        t2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 0, 0));

        t1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 0, 0));
        t1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t1KeyReleased(evt);
            }
        });

        t4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        t5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(l4)
                        .addGap(18, 18, 18)
                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(l5)
                        .addGap(31, 31, 31)
                        .addComponent(t5)
                        .addGap(38, 38, 38)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(375, 375, 375)
                        .addComponent(l2)
                        .addGap(31, 31, 31)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l3)
                    .addComponent(l4)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1130, 200));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Sr No", "Date", "Description", "Amt"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 90));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 1130, 270));

        l6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        l6.setForeground(new java.awt.Color(0, 0, 255));
        l6.setText("Total");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, -1, -1));

        t6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t6.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 230, 50));

        b2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(51, 51, 255));
        b2.setText("Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 190, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    
    private void updateTotal() {
    double total = 0.0;
//Object value = model.getValueAt(i, 3);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int rowCount = model.getRowCount();

    for (int i = 0; i < rowCount; i++) {
        Object value = model.getValueAt(i, 3); // <-- Update index based on your column

        if (value != null) {
            try {
                double amount = Double.parseDouble(value.toString());
                total += amount;
            } catch (NumberFormatException e) {
                System.out.println("Invalid amount format at row " + i + ": " + value);
            }
        }
          
    }

  t6.setText(String.valueOf(total));
}
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

// Retrieve data from text fields
        String id = t1.getText();
        String ownerName = t2.getText();
        String date = t3.getText();
        String description = t4.getText();
        String amount = t5.getText();
        String total=t6.getText();

        // Insert data into the database
        insertDataIntoDatabase(id, ownerName, date, description, amount,total);

        // Add data to the JTable
        addDataToTable(id, date, description, amount);
         updateTotal();

        // Clear the text fields after adding
        clearFields();
    }  

    private void t2KeyReleased(java.awt.event.KeyEvent evt) {
    String ownerName = t2.getText();

    if (!ownerName.isEmpty()) {
        try {
            String url = "jdbc:mysql://localhost:3306/expensetracking";
            String username = "root";
            String password = "";

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, username, password);

            String query = "SELECT id FROM expense WHERE owner_name = ? ORDER BY id DESC LIMIT 1";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, ownerName);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                String ownerId = rs.getString("id");
                t1.setText(ownerId);
            } else {
                t1.setText(""); // Clear if no match
            }

            rs.close();
            pst.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        t1.setText(""); // Clear if field is empty
    }
}


    // Method to insert data into the database
    public void insertDataIntoDatabase(String id,String ownerName, String date, String description, String amount,String total) {
        String url = "jdbc:mysql://localhost:3306/expensetracking"; // Database URL
        String username = "root"; // MySQL username
        String password = ""; // MySQL password
        
        
        

        try {
            // Step 1: Load the MySQL JDBC driver
            Class.forName("com.mysql.cj.jdbc.Driver");

            // Step 2: Establish the connection
            Connection con = DriverManager.getConnection(url, username, password);
            

            // Step 3: Create SQL insert query
            String query = "INSERT INTO expense (id, owner_name, date, description, amount,total) VALUES (?, ?, ?, ?, ?,?)";

            // Step 4: Create PreparedStatement
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, id);
            pst.setString(2, ownerName);
            pst.setString(3, date);
            pst.setString(4, description);
            pst.setString(5, amount);
            pst.setString(6, total);


            // Step 5: Execute the update
            pst.executeUpdate();
            System.out.println("Data inserted successfully.");
            JOptionPane.showMessageDialog(null, "Data inserted successfully.", "User page", 
                                           JOptionPane.INFORMATION_MESSAGE);
            
            
            
            
            
            

            
            
            
            

            // Close the connection
            pst.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Method to add data to JTable
    private void addDataToTable(String id,String date, String description, String amount) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{id, date, description, amount});
    }

    // Method to clear the input fields after adding data
    private void clearFields() {
       // t1.setText("");
        //t2.setText("");
        t4.setText("");
        t5.setText("");
    }//GEN-LAST:event_b1ActionPerformed

    
    
    private void t1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1KeyReleased
       
    }//GEN-LAST:event_t1KeyReleased

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed

      new Mdi().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JPanel p1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
